# Generated by Django 2.0 on 2017-12-13 01:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('time_of_creation', models.DateTimeField(default=datetime.datetime(2017, 12, 12, 20, 5, 29, 193367))),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('examName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Exam.Exam')),
                ('text', models.CharField(max_length=280)),
                ('nummber', models.TextField(max_length=280)),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('examName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Exam.Exam')),
                ('questionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='Exam.Question')),
                ('question', models.TextField(max_length=280)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
    ]
