# Generated by Django 2.0 on 2017-12-14 00:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('question', models.TextField(max_length=280, primary_key=True, serialize=False)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('time_of_creation', models.DateTimeField(default=datetime.datetime(2017, 12, 13, 19, 42, 26, 56341))),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('nummber', models.TextField(max_length=280)),
                ('points', models.FloatField(default=1)),
                ('examName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='examName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam'),
        ),
        migrations.AddField(
            model_name='answers',
            name='questionName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam.Question'),
        ),
    ]
