# Generated by Django 2.0 on 2017-12-14 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 22, 8, 15, 754891)),
        ),
    ]
