# Generated by Django 2.0 on 2017-12-17 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_auto_20171216_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 20, 20, 25, 682083)),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=280),
        ),
    ]
