# Generated by Django 2.0 on 2017-12-17 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_auto_20171216_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 23, 36, 51, 552302)),
        ),
    ]
