# Generated by Django 2.0 on 2017-12-18 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_auto_20171218_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 22, 4, 3, 783971)),
        ),
    ]
