# Generated by Django 2.0 on 2017-12-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_auto_20171218_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_of_creation',
            field=models.DateTimeField(default='2017-12-18T22:32:49.554265'),
        ),
    ]
